#项目路径
server:
  servlet:
    context-path: /shine
  port: 8081

spring:
  #数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.40.94.59:3306/db_rember?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: shine
    password: Shine_2019
    max-idle: 10 #指定连接池最大的空闲连接数量.
    max-wait: 10000 #指定连接池等待连接返回的最大等待时间，毫秒单位.
    min-idle: 5 #指定必须保持连接的最小值(For DBCP and Tomcat connection pools)
    initial-size: 5 #指定启动连接池时，初始建立的连接数量
    validation-query: SELECT 1 #指定获取连接时连接校验的sql查询语句.
    test-on-borrow: false #获取连接时候验证，会影响性能
    test-while-idle: true #当连接空闲时，是否执行连接测试.
    time-between-eviction-runs-millis: 18800 #指定空闲连接检查、废弃连接清理、空闲连接池大小调整之间的操作时间间隔
    mvc:
      static-path-pattern=/static/**:
  redis:
    host: 121.40.94.59
    password: Shine_2019
    port: 6379



  #显示SQL语句
  jpa:
    show-sql: true
    #Thymeleaf模板配置
    thymeleaf:
      cache: false
      prefix: /templates/
      suffix: .html

    #文件上传大小
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  rabbitmq:
    host: 121.40.94.59
    port: 5672
    username: guest
    password: guest

#FTP服务器
FTP:
  ip: 172.16.0.96
  user: shine
  password: Shine_2019
  server_path: http://172.16.0.96/
mybatis:
  type-aliases-package: com.shine.api.common.entity
  mapperLocations: classpath:mapper/*.xml
  #  mybatis.typeAliasesPackage=你的实体类包名 （例子项目的包名是com.shizhao.project.springdemo.model）
  #  mybatis.mapperLocations=classpath:mapper/*.xml
  #  logging.level.com.shizhao.project.springdemo:DEBUG
  #  server.port=你的服务端口号，要保证与其他服务不冲突，如8080